  
###configure datasource property###
spring:
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     
  datasource:
    url: jdbc:mysql://localhost:3306/department
    username: root
    password: tiger 
    driver-class-name: com.mysql.cj.jdbc.Driver  
